# site settings
title: LaPipette
subtitle:
email: contact.lapipette@gmail.com
description: Science communication & visual design — I make complex biology look beautiful.
baseurl:  # the subpath of your site, e.g. /blog
url: "https://lapipette.com" # the base hostname & protocol for your site
author:
street_address:
city:
state:
zip_code:
country:
phone:

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 10

# social settings
500px_url:
facebook_url: https://www.facebook.com/LaPipettelabs
github_url:
gitlab_url:
googleplus_url:
instagram_url: https://www.instagram.com/lapipette.labs/
linkedin_url: https://www.linkedin.com/in/etienneraimondeau/
pinterest_url:
slack_url:
twitter_url:
behance_url: https://www.behance.net/etienneraimondeau
redbubble_url: https://www.redbubble.com/people/LaPipette/

# build settings
markdown: kramdown

plugins:
  - jekyll-sitemap

sass:
  style: compressed
