# site settings
title: LaPipette
subtitle:
email: contact.lapipette@gmail.com
description: LaPipette gathers cool infographics.
baseurl:  # the subpath of your site, e.g. /blog
url: "www.lapipette.com" # the base hostname & protocol for your site
author:
street_address:
city: Oxford
state:
zip_code:
country: United Kingdom
phone:

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 10

# social settings
500px_url:
facebook_url: https://www.facebook.com/LaPipettelabs
github_url:
gitlab_url:
googleplus_url:
instagram_url: https://www.instagram.com/lapipette.labs/
linkedin_url:
pinterest_url:
slack_url:
twitter_url: https://twitter.com/LaPipettelabs
behance_url: https://www.behance.net/etienneraimondeau

# build settings
markdown: kramdown

sass:
  style: compressed
